// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnhanceText(arg1) {
  return window['go']['main']['App']['EnhanceText'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSelection() {
  return window['go']['main']['App']['GetSelection']();
}

export function HideFloatingWindow() {
  return window['go']['main']['App']['HideFloatingWindow']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function ListModels(arg1, arg2) {
  return window['go']['main']['App']['ListModels'](arg1, arg2);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function SaveSetup(arg1) {
  return window['go']['main']['App']['SaveSetup'](arg1);
}

export function ScoreOnly(arg1) {
  return window['go']['main']['App']['ScoreOnly'](arg1);
}

export function SetAutoPaste(arg1) {
  return window['go']['main']['App']['SetAutoPaste'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}

export function ShowFloatingWindow(arg1, arg2) {
  return window['go']['main']['App']['ShowFloatingWindow'](arg1, arg2);
}

export function SimulatePaste(arg1) {
  return window['go']['main']['App']['SimulatePaste'](arg1);
}

export function ValidateKey() {
  return window['go']['main']['App']['ValidateKey']();
}

export function WriteClipboard(arg1) {
  return window['go']['main']['App']['WriteClipboard'](arg1);
}
