// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EnhanceText(arg1:main.EnhanceInput):Promise<main.EnhanceResult>;

export function GetConfig():Promise<Record<string, any>>;

export function GetSelection():Promise<string>;

export function HideFloatingWindow():Promise<void>;

export function IsConfigured():Promise<boolean>;

export function ListModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ReadClipboard():Promise<string>;

export function SaveSetup(arg1:main.SetupInput):Promise<void>;

export function ScoreOnly(arg1:string):Promise<number>;

export function SetAutoPaste(arg1:boolean):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function ShowFloatingWindow(arg1:number,arg2:number):Promise<void>;

export function SimulatePaste(arg1:string):Promise<void>;

export function ValidateKey():Promise<void>;

export function WriteClipboard(arg1:string):Promise<void>;
